name: rna-seq
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - r-base=4.1
  - r-essentials
  - bioconductor-biocmanager
  - star=2.7.11b
  - fastqc=0.12.1-0
  - multiqc=1.20
  - r-subread
  - gatk=3.8
  - picard=3.1.1
  - samtools=1.20

  
